services:
  mysql:
    container_name: mysql-snippetbox
    image: mysql
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"